add login and registration component
santoshyadavdev/ng-bank pull request #31
Opened 2023-09-30 21:27 UTC by santoshyadavdev

- [x] Add login component 
- [x] Add registration component 
- [ ] Add AppWrite for Authentication
- [x] Add NgRx Store

2023-10-15 08:23 UTC, mathisvester commented on libs/user/store/src/lib/login.service.ts
> +    return this.http.post<User>(
@santoshyadavdev this request returns a Session instead of User response: https://appwrite.io/docs/references/cloud/models/session.

2023-10-15 08:24 UTC, mathisvester commented on libs/user/store/src/lib/login.service.ts
> +    return this.http.delete(`${environment.apiEndpoint}/account/sessions`, {
@santoshyadavdev currently not working.

2023-10-15 08:26 UTC, mathisvester commented on apps/ngbank/src/app/app.config.ts
> +    provideStore(),
@santoshyadavdev would it be better to provide feature state in the `user.route.ts`?

2023-10-15 08:31 UTC, mathisvester requested changes

2023-10-15 08:31 UTC, mathisvester commented on libs/user/store/src/lib/store/user.effects.ts
> +export const snackBarAfterError$ = createEffect(
Move to Effect directly.

2024-01-26 22:47 UTC, santoshyadavdev commented
@mathisvester I am thinking about merging all existing code into main, WDYT?

2024-01-27 07:41 UTC, mathisvester commented
@santoshyadavdev that's fine for me 👍🏻

2024-01-28 22:39 UTC, merged